import type { GetServerSideProps, NextPage } from 'next';
import { useDispatch, useSelector } from 'react-redux';
import userSlice, {
  IUserState,
  setUser,
  User,
  userSelector,
} from '@/store/slices/user.slice';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../../styles/Home.module.css';
import { useEffect } from 'react';
import { axiosClient } from '@/utils/axios';
import { ensureAuth } from '@/utils/ensureAuth';
import Layout from '@/components/Layout';
import { PageComponent } from 'interfaces';
import Link from 'next/link';

interface LoginProps {
  user: User;
}

const Login: PageComponent = () => {
  const user = useSelector(userSelector);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>
          Login page{' '}
          <Link href='/'>
            <a>index</a>
          </Link>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

Login.Layout = Layout;
export default Login;
