import type { GetServerSideProps, NextPage } from 'next';
import {useDispatch, useSelector} from 'react-redux';
import userSlice, { IUserState, setUser, User, userSelector } from '@/store/slices/user.slice';
import Head from 'next/head';
import Image from 'next/image';
import { AppState, wrapper } from '../store';
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';
import { axiosClient } from '@/utils/axios';

interface HomeProps  {
	user:User;
}

const Home:NextPage<HomeProps> = () => {
	const user = useSelector(userSelector);
	const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
				<h1>{user.name}</h1>
				<button onClick={()=>{
					dispatch(setUser({
						name: 'kurwa',
						id: 45,
						email: 'email@email.com',
						avatar:
							'https://pbs.twimg.com/profile_images/1045580248467886080/_uwwJdr3.jpg',
					}))
				}}>change user</button>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps(
  (store) => async (ctx) => {
    const user: User = {
      name: 'sereg',
      id: 45,
      email: 'email@email.com',
      avatar:
        'https://pbs.twimg.com/profile_images/1045580248467886080/_uwwJdr3.jpg',
    };
    store.dispatch(setUser(user));
    return {
      props: {user},
    };
  }
);
